[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../parser" }
types = { path = "../types" }
errors = { path = "../errors" }
vm = { path = "../vm" }
instructions = { path = "../instructions" }

